format = """
[](#9A348E)\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
[](fg:#86BBD8 bg:#06969A)\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
[](fg:#06969A bg:#33658A)\
$cmd_duration\
[](fg:#33658A)\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character
"""
command_timeout = 600
add_newline = false

[status]
symbol = "× "
disabled = false

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 2
truncate_to_repo = false
truncation_symbol = "…/"
repo_root_style = "bold underline bg:#DA627D"
repo_root_format = "[ $before_root_path]($style)[$repo_root]($repo_root_style)[$path ]($style)[$read_only]($read_only_style)"
style = "bg:#DA627D fg:#E0FFE0"
format = "[ $path ]($style)"
# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~/Prog/gigas" = ""
"~/Prog" = ""
"~/Documents" = ""
"~/Downloads" = ""
"~/Music" = ""
"~/Pictures" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[jobs]
symbol = "⚒ "
number_threshold = 1
symbol_threshold = 1

[username]
show_always = false
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[package]
symbol = "📦"
style = "bg:#FCA17D fg:#101010"
format = '[$symbol$version ]($style)'

# Programming languages
[c]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[cmake]
symbol = "△"
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[deno]
symbol = "🦕"
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[elixir]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[elm]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[git_branch]
truncation_length = 16
symbol = " "
style = "bg:#FCA17D fg:#101010"
format = '[ $symbol$branch ]($style)'

[git_commit]
style = "bg:#FCA17D fg:#101010"
format = '[ \($hash$tag\) ]($style)'

[git_metrics]
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'

[git_state]
style = "bg:#FCA17D fg:#101010"
format = '[\($state($progress_current/$progress_total)\)]($style)'

[git_status]
style = "bg:#FCA17D fg:#101010"
format = '[$all_status$ahead_behind]($style)'

[golang]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[java]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[julia]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[nim]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
not_capable_style = "bg:#86BBD8 fg:#FF2000"
format = '[ $symbol($version) ]($style)'

[kotlin]
symbol = "🅺"
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[lua]
symbol = "🌙"
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[perl]
symbol = "🐪"
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[php]
symbol = "🐘"
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[python]
symbol = "🐍"
style = "bg:#86BBD8 fg:#101010"
format = '[ ${symbol}${pyenv_prefix}(${version} )(👾$virtualenv )]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[scala]
symbol = ""
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

[zig]
symbol = "↯"
style = "bg:#86BBD8 fg:#101010"
format = '[ $symbol($version) ]($style)'

# Environment
[cmd_duration]
style = "bg:#33658A"
format = '[took ]($style)[$duration]($style bold yellow)'

[docker_context]
symbol = ""
style = "bg:#06969A fg:#101010"
format = '[ $symbol $context ]($style) $path'

[custom.docker-compose]
command = """switch $COMPOSE_FILE
case '*/gigas_devenv/*'
    echo 
case '*'
    basename "$(dirname "$COMPOSE_FILE")"
end"""
when = """test -n "$COMPOSE_FILE""""
shell = ["fish", "--no-config"]
symbol = "🐙"
style = "bg:#06969A"
format = "[ $symbol$output ]($style)"

[sudo]
symbol = "🧙"
style = "bg:#06969A"
format = '[ $symbol ]($style)'
