[theme]
theme = "dracula"
[theme.overrides]
separator = "<span font='11'></span>"

[icons]
icons = "material-nf"
[icons.overrides]
memory_swap = "󰾵"

[[block]]
block = "focused_window"
driver = "sway_ipc"
[block.format]
full = " $title.str(max_w:50) |"
short = " $title.str(max_w:20) |"

[[block]]
block = "external_ip"
format = "$ip.str(max_w:15,rot_interval:0.4)"
interval = 600
use_ipv4 = true
error_format = "$short_error_message.str(max_w:15)|X"
error_interval = 1
[block.theme_overrides]
idle_bg = "#19FF70"
idle_fg = "#101010"

[[block]]
block = "net"
interval = 5
# format = "$icon ^icon_net_down $speed_down.eng(3,B,K) ^icon_net_up $speed_up.eng(3,B,K) {$signal_strength $ssid |}$ip"
[block.format]
full = "$icon ^icon_net_down $graph_down.str(max_w:5) ^icon_net_up $graph_up.str(max_w:5) {$signal_strength $ssid |}$ip"
short = "$icon {$signal_strength $ssid |}$ip"
[[block.click]]
button = "left"
cmd = "dunstify -a i3status-rs \"Whats my ip?\" \"Public ip: $(dig +short myip.opendns.com @resolver1.opendns.com)\""
[block.theme_overrides]
idle_bg = "#2AF598"
idle_fg = "#101010"

[[block]]
block = "memory"
format = "$icon$mem_used.eng(w:1,u:B,prefix:M)/$mem_total.eng(w:1,u:B,prefix:M)"
interval = 5
warning_mem = 80
critical_mem = 95
[block.theme_overrides]
idle_bg = "#22E4AC"
idle_fg = "#101010"

[[block]]
block = "memory"
format = "$icon_swap$swap_used.eng(w:1,u:B,prefix:M)/$swap_total.eng(w:1,u:B,prefix:M)"
interval = 5
warning_swap = 80
critical_swap = 95
[block.theme_overrides]
idle_bg = "#1BD7BB"
idle_fg = "#101010"

[[block]]
block = "cpu"
interval = 1
format = "$icon$utilization.eng(w:2)"
[block.theme_overrides]
idle_bg = "#14C9CB"
idle_fg = "#101010"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "$icon$used.eng(w:2)/$total.eng(w:2)"
interval = 20
warning = 20.0
alert = 10.0
[block.theme_overrides]
idle_bg = "#0FB2D8"
idle_fg = "#101010"

[[block]]
block = "docker"
format = "$icon$running.eng(w:1)/$total.eng(w:1)"
interval = 10
[block.theme_overrides]
idle_bg = "#089BE5"
idle_fg = "#101010"

[[block]]
block = "temperature"
interval = 10
format = "$icon{$min≤$average≤$max|}"
[block.theme_overrides]
idle_bg = "#0384F1"
idle_fg = "#101010"

[[block]]
block = "sound"
format = "$icon{$volume.eng(w:2)|}"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
[block.format]
full = "$icon$timestamp.datetime(f:'%m\\%d %a %R', l:es_ES)"
short = "$icon$timestamp.datetime(f:'%m\\%d %R', l:es_ES)"
[block.theme_overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[[block]]
block = "custom"
interval = 10
format = "$text.pango-str()"
command = """ps -do args|sed -n "s|^/bin/sh $HOME/bin/daemon-gigas-vpn\\$||p;s|^./remap -C .*|󰞙|p"|tr -d '\n'"""
merge_with_next = true

[[block]]
block = "battery"
interval = 10
driver = "upower"
format = "$icon $percentage $time"
