gui:
  scrollHeight: 5
  showBottomLine: false
  screenMode: "half"
logs:
  since: ''
  tail: 512
commandTemplates:
  dockerCompose: docker compose
customCommands:
  containers:
    - name: gigas CORE   up
      attach: false
      command: '{{ .DockerCompose }} up -d db_maria db_mysql db_redis rabbitmq websockifier id-provider'
      serviceNames: []
    - name: gigas CORE   stop
      attach: false
      command: '{{ .DockerCompose }} stop  db_maria db_mysql db_redis rabbitmq websockifier id-provider'
      serviceNames: []
    - name: gigas MAPP   up
      attach: false
      command: '{{ .DockerCompose }} up -d apiproxy api-kvm api-vmware api-oracle mapp router'
      serviceNames: []
    - name: gigas MAPP   stop
      attach: false
      command: '{{ .DockerCompose }} stop  apiproxy api-kvm api-vmware api-oracle mapp router'
      serviceNames: []
    - name: gigas KVM    up
      attach: false
      command: '{{ .DockerCompose }} up -d apiproxy api-kvm kudeiro-kvm executor-kvm uploader-kvm controlpanel hapi router'
      serviceNames: []
    - name: gigas KVM    stop
      attach: false
      command: '{{ .DockerCompose }} stop  apiproxy api-kvm kudeiro-kvm executor-kvm uploader-kvm controlpanel hapi router'
      serviceNames: []
    - name: gigas VMWARE up
      attach: false
      command: '{{ .DockerCompose }} up -d apiproxy api-vmware kudeiro-vmware executor-vmware uploader-vmware controlpanel hapi router'
      serviceNames: []
    - name: gigas VMWARE stop
      attach: false
      command: '{{ .DockerCompose }} stop  apiproxy api-vmware kudeiro-vmware executor-vmware uploader-vmware controlpanel hapi router'
      serviceNames: []
    - name: gigas ORACLE up
      attach: false
      command: '{{ .DockerCompose }} up -d apiproxy api-oracle kudeiro-oracle executor-oracle uploader-oracle controlpanel hapi router'
      serviceNames: []
    - name: gigas ORACLE stop
      attach: false
      command: '{{ .DockerCompose }} stop  apiproxy api-oracle kudeiro-oracle executor-oracle uploader-oracle controlpanel hapi router'
      serviceNames: []
